  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1    Fe24     O69      1.95691       0   0   0           -0.49454 
      2    Ni54     O69      2.04273       0   0   0           -0.34069 
      3    Ni56     O69      2.02283       0   0   0           -0.36809 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1    Fe24     O69      1.95691       0   0   0           -1.01225 
      2    Ni54     O69      2.04273       0   0   0           -0.51370 
      3    Ni56     O69      2.02283       0   0   0           -0.53557 
