  COOP#  atomMU  atomNU     distance     translation      ICOOP (at) eF   for spin  1
      1    Fe24     O69      1.95691       0   0   0           -0.01665 
      2    Ni54     O69      2.04273       0   0   0           -0.01695 
      3    Ni56     O69      2.02283       0   0   0           -0.01518 
  COOP#  atomMU  atomNU     distance     translation      ICOOP (at) eF   for spin  2
      1    Fe24     O69      1.95691       0   0   0            0.00813 
      2    Ni54     O69      2.04273       0   0   0           -0.01223 
      3    Ni56     O69      2.02283       0   0   0           -0.01454 
