  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1    Fe24     O69      2.03065       0   0   0           -0.41978 
      2    Fe28     O69      2.04580       0   0   0           -0.43360 
      3    Fe40     O69      2.04604       0   0   0           -0.43410 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1    Fe24     O69      2.03065       0   0   0           -0.77214 
      2    Fe28     O69      2.04580       0   0   0           -0.65106 
      3    Fe40     O69      2.04604       0   0   0           -0.65012 
