  COOP#  atomMU  atomNU     distance     translation      ICOOP (at) eF   for spin  1
      1    Fe24     O69      2.03065       0   0   0           -0.01225 
      2    Fe28     O69      2.04580       0   0   0           -0.01826 
      3    Fe40     O69      2.04604       0   0   0           -0.01784 
  COOP#  atomMU  atomNU     distance     translation      ICOOP (at) eF   for spin  2
      1    Fe24     O69      2.03065       0   0   0           -0.00492 
      2    Fe28     O69      2.04580       0   0   0           -0.01748 
      3    Fe40     O69      2.04604       0   0   0           -0.01774 
